CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL,
    unique(name),
    unique(email)
);

CREATE TABLE IF NOT EXISTS categories(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    unique(name)
);

CREATE TABLE IF NOT EXISTS events(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_on_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on_date TIMESTAMP WITHOUT TIME ZONE,
    state VARCHAR(10),
    longitude FLOAT NOT NULL,
    latitude FLOAT NOT NULL,
    paid BOOLEAN DEFAULT FALSE,
    participant_limit INTEGER DEFAULT 0,
    request_moderation BOOLEAN DEFAULT TRUE,
    category_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT,
    initiator_id BIGINT,
    confirmed_reqs BIGINT,
    CONSTRAINT fk_initiator_id FOREIGN KEY (initiator_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS requests(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id BIGINT,
    status VARCHAR(10),
    CONSTRAINT fk_requester_id FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);